dist: xenial

language: python

python:
  - "3.7"

cache: pip

install:
  - pip install .[test]
  - pip install codecov

script: pytest

after_success:
  - coverage combine
  - codecov

notifications:
  email: false
